In [1]:
import numpy as np

In [2]:
a = np.array([-3,-2,-1,0,1,2,3])
print(a,a.dtype)

[-3 -2 -1  0  1  2  3] int32


In [3]:
a = np.array([-3,-2,-1,0,1,2,3], dtype='bool_')
print(a,a.dtype)

[ True  True  True False  True  True  True] bool


In [4]:
a = np.array([-3,-2,-1,0,1,2,3], dtype='uint16')
print(a,a.dtype)

[65533 65534 65535     0     1     2     3] uint16


In [5]:
a = np.array([-3.9,-2.7,-1.6,0,1.,2.4,3.5])
print(a,a.dtype)

[-3.9 -2.7 -1.6  0.   1.   2.4  3.5] float64


In [6]:
a = np.array([1.1,2.2+3.3j,4.4j])
print(a,a.dtype)

[1.1+0.j  2.2+3.3j 0. +4.4j] complex128


In [7]:
a = np.timedelta64(9, 'D')
print(a,a.dtype)

9 days timedelta64[D]


In [8]:
a=np.array(['2019-04-21', '2014-04-18', '2011-06-21'], dtype='datetime64')
print(a,a.dtype)

['2019-04-21' '2014-04-18' '2011-06-21'] datetime64[D]


In [9]:
a = np.array([27,56,98], dtype='O')
print(a,a.dtype)

[27 56 98] object


In [10]:
a = np.array(['kumar', 'SRM', 'CSE'])
print(a, a.dtype)

['kumar' 'SRM' 'CSE'] <U5


In [11]:
a = np.array([u'\u1F600',u'\u2202r',u'\u1F609'], dtype='U')
print(a,a.dtype)

['ὠ0' '∂r' 'ὠ9'] <U2
